const lang = {
  LANG01: "all",
  LANG02: "home",
  LANG03: "Terms of Service",
  LANG04: "privacy policy",
  LANG05: "Log out",
  LANG06: "login",
  LANG07: "Personalization",
  LANG08: "deal",
  LANG09: "purchase",
  LANG10: "sale",
  LANG11: "My transaction",
  LANG12: "Depression",
  LANG13: "Reserve assets",
  LANG14: "Depression",
  LANG15: "customer service center",
  LANG16: "Notice",
  LANG17: "1: 1 inquiry",
  LANG18: "Logged out",
  LANG19: "Sign Up",
  LANG20: "Language settings",
  LANG21: "welcome.",
  LANG22: "Login",
  LANG23: "Coin",
  LANG24: "quote",
  LANG25: "Holding Quantity",
  LANG26: "Available quantity",
  LANG27: "Quantity",
  LANG28: "Transaction number",
  LANG29: "Registration date",
  LANG30: "ID",
  LANG40: "Buying quantity",
  LANG41: "Purchase currency",
  LANG42: "Purchase price",
  LANG43: "Seller Bank",
  LANG44: "Seller account number",
  LANG45: "Seller Deposit",
  LANG46: "Purchase deposit",
  LANG47: "List",
  LANG48: "Confirmation of deposit",
  LANG49: "Contact your file-up load failure manager",
  LANG50: "Purchase deposit was processed normal.",
  LANG51: "The purchase deposit failed.",
  LANG52: "certification",
  LANG53: "Number + Include special characters, input for more than 6 digits",
  LANG54: "The password is different.",
  LANG55: "Confirm",
  LANG56: "go back",
  LANG57: "Date",
  LANG58: "title",
  LANG59: "look",
  LANG60: "Sort by",
  LANG61: "Trading quantity",
  LANG62: "Transaction time",
  LANG63: "Reverse",
  LANG64: "Quantity",
  LANG65: "purchase",
  LANG66: "call",
  LANG67: "price",
  LANG68: "sale",
  LANG69: "Purchase",
  LANG70: "Sales gun",
  LANG71: "Exchange use guide",
  LANG72: "Meet a simple and fast digital asset exchange from coin information to your order.",
  LANG73: "How to use Exchange",
  LANG74: "Frequently asked questions",
  LANG75: "Take a tour of the exchange",
  LANG76: "Customer",
  LANG77: "Business door",
  LANG78: "Please write details. Please attach the text editor to use.",
  LANG79: "writing",
  LANG80: "Please enter all of the values",
  LANG81: "Finished appointment",
  LANG82: "An unknown error",
  LANG83: "number",
  LANG84: "Contact state",
  LANG85: "date",
  LANG86: "There are no questions you have created.",
  LANG87: "Checking inquiry",
  LANG88: "Complete answers",
  LANG89: "Payment call",
  LANG90: "It is already a registered economic call.",
  LANG91: "Account Holder",
  LANG92: "Deposit address",
  LANG93: "Other information",
  LANG94: "Bank",
  LANG95: "Adding",
  LANG96: "Contact the Load File Manager!",
  LANG97: "Please enter all of the values",
  LANG98: "Additional completion",
  LANG99: "Additional failure",
  LANG100: "Please enter a deposit address or account.",
  LANG101: "Please select a bank!",
  LANG102: "Please enter your deposit stock",
  LANG103: "Please enter your account number or wallet address!",
  LANG104: "Administrator inquiry",
  LANG105: "Profile",
  LANG106: "name",
  LANG107: "address",
  LANG108: "QR code",
  LANG109: "management",
  LANG110: "delete",
  LANG111: "change",
  LANG112: "Adding",
  LANG113: "Country selection",
  LANG114: "Modify member information",
  LANG115: "Change completion",
  LANG116: "Change failed",
  LANG117: "Existing password is not correct",
  LANG118: "Order registration",
  LANG119: "Select Custom Type",
  LANG120: "Coin to deal",
  LANG121: "method of payment",
  LANG122: "Price type",
  LANG123: "Classification",
  LANG124: "Fixed applied",
  LANG125: "estimated price",
  LANG126: "Total trading quantity",
  LANG127: "Total trading amount",
  LANG128: "Enrollment",
  LANG129: "Normal order processed.",
  LANG130: "Registration failed.",
  LANG131: "The coin is insufficient.",
  LANG132: "The fee is not enough coin.",
  LANG133: "Sales registration failed.",
  LANG134: "Sales fee",
  LANG135: "state",
  LANG136: "Purchase Application",
  LANG137: "Sales Application",
  LANG138: "Complete trading",
  LANG139: "Transaction waiting",
  LANG140: "In trading",
  LANG141: "Cancellation of transaction",
  LANG142: "The purchase application has been summed up",
  LANG143: "The sales application has been received normally. Please deposit the seller!",
  LANG144: "Please try again!",
  LANG145: "I have already applied.",
  LANG146: "Fee lacks coin balance",
  LANG147: "Any problem occurrence (administrator inquiry)",
  LANG148: "registrant",
  LANG149: "Application for transactions",
  LANG150: "Complete trading",
  LANG151: "Checking deposit",
  LANG152: "My transaction",
  LANG153: "order",
  LANG154: "Proceeding",
  LANG155: "complete",
  LANG156: "Canceled",
  LANG157: "Total Trading",
  LANG158: "division",
  LANG159: "The coin address is not generated and moves to the coin generation pages.",
  LANG160: "Did you forget your ID?",
  LANG161: "find ID",
  LANG162: "Forgot your password?",
  LANG163: "find password",
  LANG164: "Invalid account information",
  LANG165: "Are not you a member?",
  LANG166: "ID inputs for 6 digits including English + numbers",
  LANG167: "send",
  LANG168: "Please select a country",
  LANG169: "The authorization number has been sent",
  LANG170: "This ID is already taken",
  LANG171: "It is a cell phone number already in use.",
  LANG172: "Contact the Server Error Manager",
  LANG173: "Thank you for joining the global bit",
  LANG174: "Registration ID",
  LANG175: "It is already subscribed",
  LANG176: "Certification number issued 5 minutes exceeded",
  LANG177: "Please publish the certification number again",
  LANG178: "The authentication number is not correct.",
  LANG179: "Members failed",
  LANG180: "Invalid value input",
  LANG181: "Overdue address",
  LANG182: "Transaction ID",
  LANG183: "fees",
  LANG184: "Deposit in progress",
  LANG185: "deposit",
  LANG186: "withdraw",
  LANG187: "Deposit history",
  LANG188: "Overview",
  LANG189: "Overdrive",
  LANG190: "Possible quantity",
  LANG191: "Payment fee",
  LANG192: "OTP authentication number",
  LANG193: "OTP registration",
  LANG194: "OTP authentication failed",
  LANG195: "Please proceed with address certification first",
  LANG196: "Normal transmission processed",
  LANG197: "Lack of balance",
  LANG198: "Lack of amount",
  LANG199: "Please try to send it again.",
  LANG200: "I have exceeded the daily limit",
  LANG201: "We have exceeded the monthly service",
  LANG202: "There is an onto waiting. Please apply again for a while",
  LANG203: "Not transported to system error",
  LANG204: "Identify the wrong address",
  LANG205: "It is an origin available.",
  LANG206: "Create Address",
  LANG207: "The address has been completed.",
  LANG208: "Additional failure",
  LANG209: "There is an already registered address.",
  LANG210: "wrong address",
  LANG211: "Normal processing.",
  LANG212: "Confirmation of payment",
  LANG213: "Deposit information",
  LANG214: "Login is required.",
  LANG215: "transmission error",
  LANG216: "Membership",
  LANG217: "Security function and google otp",
  LANG218: "Deposit/Withdrawal",
  LANG219: "Use of Services",
  LANG220: "Cxgotc p2p trading method",
  LANG221: "Anyone can sign up for Cxgotc membership as long as they have their own mobile phone number",
  LANG222: "Click the member registration tab on the top right, select your country of residence, enter your ID and password to use",
  LANG223: "After entering your mobile phone number, click the send button to send the verification code",
  LANG224: "Enter the verification code you received through text message to complete membership registration",
  LANG225: "(If the verification code has not arrived, please try again with a delay)",
  LANG226: "(If the verification code has not arrived, please try again with a delay)",
  LANG227: "The mobile phone verification text did not come.",
  LANG228: "If any of the following apply, the authentication text may not be received properly, so please check",
  LANG229: "In case of blocking reception of information provider number",
  LANG230: "If anti-spam app is installed",
  LANG231: "I forgot my login password.",
  LANG232: "How to change password",
  LANG233: "Find password in the middle of the login screen → Enter ID and complete authentication of registered mobile phone number → Reset password after authentication is complete",


  LANG234: "I want to cancel my membership.",
  LANG235: "When you cancel your membership, your cxgotc usage information is deleted and cannot be recovered, so please choose carefully.",
  LANG236: "Can I join as a corporate member?",


  LANG237: "Cxgotc cannot be registered as a corporate member",
  LANG240: "Is it possible to join even if I don't have a mobile phone under my name?",
  LANG239: "Cxgotc can only be signed up with a mobile phone under your name.",


  LANG240: "Can foreigners use it?",
  LANG241: "Cxgotc is a global cryptocurrency exchange",
  LANG242: "Even a foreigner can sign up and use a mobile phone under his/her name",
  LANG243: "When you sign up as a member, it says that you have already registered a number",

  LANG251: "Cxgotc is one mobile phone number",
  LANG252: "Only one account can complete identity verification",
  LANG253: "If you are not a member of cxgotc, please join",
  LANG254: "If the same message appears during authentication",
  LANG255: "Customer Center 1:1 inquiry or admin email",
  LANG256: "Please contact us at (cxgotc@gmail.com)",
  LANG257: "Theft of virtual assets and reporting accidents",
  LANG258: "If there is a transaction history, login, or cryptocurrency transfer that you did not do",
  LANG259: "Please immediately contact the cxgotc customer center 1:1 inquiry and admin email (cxgotc@gmail.com)",
  LANG260: "What is Google otp authentication?",
  LANG261: "This is an authentication method that uses a one-time password that is randomly generated at regular intervals instead of a fixed password",
  LANG262: "It is mandatory authentication because most hacking attempts can be blocked through google otp.",
  LANG263: "Where can I check the deposit and withdrawal?",
  LANG264: "You can check the deposit and withdrawal details in the deposit/withdrawal history at the top of the homepage",
  LANG265: "Where do I check my holdings?",
  LANG266: "You can check the details of your assets in Deposit and Withdraw → Assets held at the top",
  LANG267: "How do I deposit virtual assets?",

  LANG268: "When depositing virtual assets in other exchanges with cxgotc, create a deposit address in the deposit and withdrawal section at the top and write it down in the withdrawal column of other exchanges.",
  LANG269: "Deposit to cxgotc",
  LANG270: "(The time required for deposit may vary for each virtual asset, but usually takes within 10 to 60 minutes)",
  LANG271: "※However, if there is an excessive accumulation of unauthorized transactions in the blockchain network, the deposit may be delayed due to the delay in confirmation on the network",
  LANG272: "How do I withdraw virtual assets?",
  LANG273: "When withdrawing your virtual assets from Cxgotc, click the withdrawal tab at the top of the deposit/withdrawal section, and after verifying the address and mobile phone number, press the withdrawal button to withdraw.",

  LANG274: "I want to cancel the withdrawal of virtual assets.",
  LANG275: "Currently, it is impossible for a member to cancel a withdrawal after applying for withdrawal",
  LANG276: "Is cxgotc available overseas?",
  LANG277: "cxgotc is also available overseas.",
  LANG278: "However, mobile phone authentication must be completed for safe and smooth transactions.",
  LANG279: "(Requires a mobile phone that can be authenticated by mobile phone, and can be used even in roaming state)",
  LANG280: "Are there any restrictions on service use?",
  LANG281: "Transactions may be restricted if fraud or money laundering is suspected.",
  LANG282: "I want to restore my Cxgotc account.",

  LANG283: "Personal information of accounts that have completed membership withdrawal will be permanently deleted immediately upon withdrawal",
  LANG284: "Accounts that have been withdrawn once cannot be recovered",
  LANG285: "I want to buy a virtual asset",
  LANG286: "If you want to purchase a virtual asset, you can register for purchase of the virtual asset you want to purchase by registering an order in the upper transaction → Purchase tab.",
  LANG286: "I want to sell virtual assets.",
  LANG287: "If you want to sell your virtual assets, you can register your virtual assets for sale at the desired price by registering an order in the upper transaction → Sales tab.",
  LANG288: "I want to cancel my order.",
  LANG289: "You can cancel and modify orders in the Transactions → My Transactions tab at the top of the homepage.",
  LANG290: "How much is the transaction fee?",
  LANG291: "The transaction fee is 1%.",
  LANG292: "When purchasing and selling, 1% of the order amount (quantity) is paid as a commission.",
  LANG293: "Placed orders cannot be modified or canceled.",
  LANG294: "An unfulfilled order can be canceled and re-ordered.",

};
module.exports = lang;